[package]
name = "maestro"
version = "0.1.0"
authors = ["llenotre <llenotre@student.42.fr>"]
edition = "2021"

# The kernel is implemented into an library in order to make it accessible from kernel modules as a dependency.
[lib]
name = "kernel"
path = "src/kernel.rs"
crate-type = ["dylib", "staticlib"]

[dependencies]
macros = { path = "macros/" }

[build-dependencies]
cc = { version = "1.0.79", features = ["parallel"] }
serde = { version = "*", features = ["derive"] }
toml = "0.7.3"

[features]
default = []
strace = ["macros/strace"]

[profile.release]
lto = true
panic = "abort"
