[package]
name = "maestro"
version = "0.1.0"
authors = ["llenotre <llenotre@student.42.fr>"]
edition = "2018"

[[bin]]
name = "maestro"
path = "src/kernel.rs"

[lib]
name = "maestro"
path = "src/kernel.rs"
