cargo-features = ["profile-rustflags"]

[package]
name = "maestro"
version = "0.1.0"
authors = ["llenotre <llenotre@student.42.fr>"]
edition = "2021"

# The kernel is implemented as a shared library in order to make it accessible from kernel modules
[lib]
name = "kernel"
path = "src/kernel.rs"
crate-type = ["rlib", "dylib"]

# Export the kernel as executable
[[bin]]
name = "maestro"
path = "src/bin.rs"

[dependencies]
macros = { path = "macros/" }

[build-dependencies]
cc = { version = "1.0.79", features = ["parallel"] }
serde = { version = "*", features = ["derive"] }
serde_json = "1.0.96"
toml = "0.7.3"

[features]
default = []
strace = ["macros/strace"]

[profile.release]
lto = true
panic = "abort"
rustflags = [
	"-Clink-dead-code",
	"-Cno-redzone=yes",
]

[profile.dev]
rustflags = [
	"-Clink-dead-code",
	"-Cno-redzone=yes",

	# Specific to `dev`
	"-Cforce-frame-pointers=yes"
]
