[package]
name = "maestro"
version = "0.1.0"
authors = ["llenotre <llenotre@student.42.fr>"]
edition = "2021"
build = "build/main.rs"

# The kernel is implemented as a shared library in order to make it accessible from kernel modules
[lib]
name = "kernel"
path = "src/kernel.rs"
crate-type = ["rlib", "dylib"]

# Export the kernel as executable
[[bin]]
name = "maestro"
path = "src/bin.rs"

[dependencies]
macros = { path = "../macros" }
utils = { path = "../utils" }

[build-dependencies]
build-utils = { path = "../build-utils" }
cc = { version = "1.0.83", features = ["parallel"] }
serde = { version = "*", features = ["derive"] }
toml = "0.8.8"

[features]
default = []
memtrace = []
strace = ["macros/strace"]
