name: Check
on: [push, pull_request]
jobs:
  debug:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Compilation
        run: scripts/ci/build.sh
      - name: Check Multiboot2 for x86
        run: grub-file --is-x86-multiboot2 target/x86/debug/maestro
  release:
    runs-on: [self-hosted, linux]
    needs: debug
    steps:
      - uses: actions/checkout@v4
      - name: Compilation
        env:
          CARGOFLAGS: --release
        run: scripts/ci/build.sh
      - name: Check Multiboot2 for x86
        run: grub-file --is-x86-multiboot2 target/x86/release/maestro
  selftest:
    runs-on: [self-hosted, linux]
    needs: debug
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: scripts/ci/selftest.sh
        timeout-minutes: 10
  strace:
    runs-on: [self-hosted, linux]
    needs: debug
    steps:
      - uses: actions/checkout@v4
      - name: Compilation
        env:
          CARGOFLAGS: --features strace
        run: scripts/ci/build.sh
      - name: Check Multiboot2 for x86
        run: grub-file --is-x86-multiboot2 target/x86/debug/maestro
  format:
    runs-on: [self-hosted, linux]
    steps:
      - name: Macros
        working-directory: ./macros
        run: cargo fmt --check
      - name: Kernel
        run: cargo fmt --check
  documentation:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Build book
        run: mdbook build doc/
      - name: Build references
        run: scripts/ci/doc.sh
  clippy:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: cp default.build-config.toml build-config.toml
      - name: Macros
        working-directory: ./macros
        run: cargo clippy --all-features
      - name: Kernel
        run: cargo clippy --all-features
