name: Check
on: push
jobs:
  Format:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt --check
  Documentation:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - name: Build book
        run: "mdbook build doc/"
      - name: Build references
        # TODO support multiple architectures
        run: "cargo doc"
  Debug:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - name: Compilation
        run: "scripts/ci/build.sh"
      - name: Check Multiboot2 for x86
        # TODO support multiple architectures
        run: "grub-file --is-x86-multiboot2 target/x86/debug/maestro"
  Release:
    runs-on: [self-hosted, linux]
    needs: Debug
    steps:
      - uses: actions/checkout@v2
      - name: Compilation
        run: "CARGOFLAGS='--release' scripts/ci/build.sh"
      - name: Check Multiboot2 for x86
        # TODO support multiple architectures
        run: "grub-file --is-x86-multiboot2 target/x86/release/maestro"
  Selftest:
    runs-on: [self-hosted, linux]
    needs: Debug
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: "scripts/ci/selftest.sh"
