name: Release mode
on: push
jobs:
    Test:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v2
            - name: Compilation
              run: "testing/release.sh"
