name: Testing
on: push
jobs:
    Test:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v2
            - name: Debug mode compilation
              run: "testing/debug.sh"
            - name: Release mode compilation
              run: "testing/release.sh"
            - name: Running selftests
              run: "testing/selftest.sh"
