name: Testing
on: push
jobs:
    test:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v2
            - run: "testing/debug.sh"
            - run: "testing/release.sh"
            - run: "testing/selftest.sh"
